# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d6a507a00eddf2c5f4e557be2c74f4264d48c6e6bc574d84a4b079f9ad4b000cf25d92c2542d5fa9f46c9063ed58eb87cf43600ad86ae9dacc4b41e56c2ff8

test:
  secret_key_base: 766c6a9d0e2bc618cd26538d60d3286d9652690adfbffe839eb393293ffdfbc5f952d5a510d0f8690426eebae4a35058d48275868c0cb817264b0289cc14b398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
